//
//  CanvasView+Landscape.m
//  rs.ios.stage-task8
//
//  Created by Źmicier Fiedčanka on 16.07.21.
//

#import "CanvasView+Landscape.h"

@implementation CanvasView (Landscape)

-(void)drawLandscapeWithColors:(NSArray<UIColor*>*)colors {
    [self.shape1Layer removeFromSuperlayer];
    [self.shape2Layer removeFromSuperlayer];
    [self.shape3Layer removeFromSuperlayer];

    self.shape1Layer.strokeEnd = 0;
    self.shape1Layer.lineWidth = 1.0;
    self.shape1Layer.path = [self getMountainsVector].CGPath;
    self.shape1Layer.fillColor = UIColor.clearColor.CGColor;
    self.shape1Layer.strokeColor = colors[0].CGColor;
    self.shape1Layer.position = CGPointMake(30, 40);
    
    self.shape2Layer.strokeEnd = 0;
    self.shape2Layer.lineWidth = 0.5;
    self.shape2Layer.path = [self getHillsVector].CGPath;
    self.shape2Layer.fillColor = UIColor.clearColor.CGColor;
    self.shape2Layer.strokeColor = colors[1].CGColor;
    self.shape2Layer.position = CGPointMake(31.5, 112);
    
    self.shape3Layer.strokeEnd = 0;
    self.shape3Layer.lineWidth = 1.0;
    self.shape3Layer.path = [self getGrassVector].CGPath;
    self.shape3Layer.fillColor = UIColor.clearColor.CGColor;
    self.shape3Layer.strokeColor = colors[2].CGColor;
    self.shape3Layer.position = CGPointMake(28, 154);

    [self.layer addSublayer:self.shape1Layer];
    [self.layer addSublayer:self.shape2Layer];
    [self.layer addSublayer:self.shape3Layer];
}

- (UIBezierPath*)getMountainsVector {
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(229, 102)];
    [bezierPath addLineToPoint: CGPointMake(235.5, 111.5)];
    [bezierPath addLineToPoint: CGPointMake(248, 124)];
    [bezierPath addLineToPoint: CGPointMake(247, 107.5)];
    [bezierPath addLineToPoint: CGPointMake(244.5, 92)];
    [bezierPath addLineToPoint: CGPointMake(239.5, 78.5)];
    [bezierPath addLineToPoint: CGPointMake(235.5, 70)];
    [bezierPath addLineToPoint: CGPointMake(231.5, 62.5)];
    [bezierPath addLineToPoint: CGPointMake(225.5, 54)];
    [bezierPath addLineToPoint: CGPointMake(220.5, 53.5)];
    [bezierPath addLineToPoint: CGPointMake(218, 53.5)];
    [bezierPath addLineToPoint: CGPointMake(214, 54)];
    [bezierPath addLineToPoint: CGPointMake(210, 55.5)];
    [bezierPath addLineToPoint: CGPointMake(206.5, 53.5)];
    [bezierPath addLineToPoint: CGPointMake(203.5, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(199.5, 53.5)];
    [bezierPath addLineToPoint: CGPointMake(194.5, 53.5)];
    [bezierPath addLineToPoint: CGPointMake(190, 55.5)];
    [bezierPath addLineToPoint: CGPointMake(187, 54)];
    [bezierPath addLineToPoint: CGPointMake(183, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(179, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(172, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(165.5, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(162.5, 54)];
    [bezierPath addLineToPoint: CGPointMake(156, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(150, 52.5)];
    [bezierPath addLineToPoint: CGPointMake(146, 51.5)];
    [bezierPath addLineToPoint: CGPointMake(140.5, 53.5)];
    [bezierPath addLineToPoint: CGPointMake(137, 51.5)];
    [bezierPath addLineToPoint: CGPointMake(130, 51.5)];
    [bezierPath addLineToPoint: CGPointMake(135.5, 50)];
    [bezierPath addLineToPoint: CGPointMake(139, 47)];
    [bezierPath addLineToPoint: CGPointMake(140.5, 45)];
    [bezierPath addLineToPoint: CGPointMake(143.5, 42.5)];
    [bezierPath addLineToPoint: CGPointMake(146, 39)];
    [bezierPath addLineToPoint: CGPointMake(150, 39)];
    [bezierPath addLineToPoint: CGPointMake(157.5, 39)];
    [bezierPath addLineToPoint: CGPointMake(163, 39)];
    [bezierPath addLineToPoint: CGPointMake(168, 36)];
    [bezierPath addLineToPoint: CGPointMake(170, 32)];
    [bezierPath addLineToPoint: CGPointMake(176.5, 31)];
    [bezierPath addLineToPoint: CGPointMake(180, 33.5)];
    [bezierPath addLineToPoint: CGPointMake(184, 32)];
    [bezierPath addLineToPoint: CGPointMake(188, 33.5)];
    [bezierPath addLineToPoint: CGPointMake(190, 29.5)];
    [bezierPath addLineToPoint: CGPointMake(194.5, 27.5)];
    [bezierPath addLineToPoint: CGPointMake(200.5, 27.5)];
    [bezierPath addLineToPoint: CGPointMake(190, 20)];
    [bezierPath addLineToPoint: CGPointMake(176.5, 12.5)];
    [bezierPath addLineToPoint: CGPointMake(159, 5.5)];
    [bezierPath addLineToPoint: CGPointMake(139, 1.5)];
    [bezierPath addLineToPoint: CGPointMake(123.5, 0.5)];
    [bezierPath addLineToPoint: CGPointMake(106.5, 1.5)];
    [bezierPath addLineToPoint: CGPointMake(90, 4)];
    [bezierPath addLineToPoint: CGPointMake(77, 9)];
    [bezierPath addLineToPoint: CGPointMake(65.5, 14)];
    [bezierPath addLineToPoint: CGPointMake(71, 17)];
    [bezierPath addLineToPoint: CGPointMake(75, 21)];
    [bezierPath addLineToPoint: CGPointMake(78, 26.5)];
    [bezierPath addLineToPoint: CGPointMake(78.5, 32)];
    [bezierPath addLineToPoint: CGPointMake(75, 40)];
    [bezierPath addLineToPoint: CGPointMake(69.5, 45)];
    [bezierPath addLineToPoint: CGPointMake(65.5, 47)];
    [bezierPath addLineToPoint: CGPointMake(61, 47)];
    [bezierPath addLineToPoint: CGPointMake(54, 44)];
    [bezierPath addLineToPoint: CGPointMake(49, 40)];
    [bezierPath addLineToPoint: CGPointMake(45.5, 33.5)];
    [bezierPath addLineToPoint: CGPointMake(45.5, 27.5)];
    [bezierPath addLineToPoint: CGPointMake(33, 38.5)];
    [bezierPath addLineToPoint: CGPointMake(24.5, 48.5)];
    [bezierPath addLineToPoint: CGPointMake(17, 60)];
    [bezierPath addLineToPoint: CGPointMake(11.5, 71)];
    [bezierPath addLineToPoint: CGPointMake(10, 77)];
    [bezierPath addLineToPoint: CGPointMake(13.5, 77)];
    [bezierPath addLineToPoint: CGPointMake(17, 76)];
    [bezierPath addLineToPoint: CGPointMake(23.5, 80)];
    [bezierPath addLineToPoint: CGPointMake(29.5, 80)];
    [bezierPath addLineToPoint: CGPointMake(35.5, 85)];
    [bezierPath addLineToPoint: CGPointMake(39, 84)];
    [bezierPath addLineToPoint: CGPointMake(44, 86.5)];
    [bezierPath addLineToPoint: CGPointMake(41.5, 87.5)];
    [bezierPath addLineToPoint: CGPointMake(35.5, 89)];
    [bezierPath addLineToPoint: CGPointMake(30.5, 88)];
    [bezierPath addLineToPoint: CGPointMake(28.5, 89)];
    [bezierPath addLineToPoint: CGPointMake(24.5, 89)];
    [bezierPath addLineToPoint: CGPointMake(21.5, 89)];
    [bezierPath addLineToPoint: CGPointMake(19.5, 91)];
    [bezierPath addLineToPoint: CGPointMake(17.5, 90)];
    [bezierPath addLineToPoint: CGPointMake(15.5, 90)];
    [bezierPath addLineToPoint: CGPointMake(10, 87.5)];
    [bezierPath addLineToPoint: CGPointMake(4.5, 90)];
    [bezierPath addLineToPoint: CGPointMake(2, 98.5)];
    [bezierPath addLineToPoint: CGPointMake(0, 124.5)];
    [bezierPath addLineToPoint: CGPointMake(4.5, 154.5)];
    [bezierPath addLineToPoint: CGPointMake(11.5, 147.5)];
    [bezierPath addLineToPoint: CGPointMake(17, 143.5)];
    [bezierPath addLineToPoint: CGPointMake(28.5, 131)];
    [bezierPath addLineToPoint: CGPointMake(39, 119.5)];
    [bezierPath moveToPoint: CGPointMake(229, 102)];
    [bezierPath addLineToPoint: CGPointMake(218, 107.5)];
    [bezierPath moveToPoint: CGPointMake(229, 102)];
    [bezierPath addLineToPoint: CGPointMake(227.17, 111.5)];
    [bezierPath addLineToPoint: CGPointMake(227.17, 123)];
    [bezierPath moveToPoint: CGPointMake(218, 107.5)];
    [bezierPath addLineToPoint: CGPointMake(206.5, 84)];
    [bezierPath addLineToPoint: CGPointMake(198, 76.5)];
    [bezierPath addLineToPoint: CGPointMake(190, 86.5)];
    [bezierPath addLineToPoint: CGPointMake(179, 99)];
    [bezierPath addLineToPoint: CGPointMake(174.5, 96.5)];
    [bezierPath addLineToPoint: CGPointMake(157.5, 114.5)];
    [bezierPath addLineToPoint: CGPointMake(143.5, 135)];
    [bezierPath moveToPoint: CGPointMake(218, 107.5)];
    [bezierPath addLineToPoint: CGPointMake(222, 114.5)];
    [bezierPath addLineToPoint: CGPointMake(227.17, 123)];
    [bezierPath moveToPoint: CGPointMake(143.5, 135)];
    [bezierPath addLineToPoint: CGPointMake(135.5, 126)];
    [bezierPath addLineToPoint: CGPointMake(115, 106)];
    [bezierPath addLineToPoint: CGPointMake(107.5, 86.5)];
    [bezierPath addLineToPoint: CGPointMake(103, 86.5)];
    [bezierPath addLineToPoint: CGPointMake(96.5, 76.5)];
    [bezierPath moveToPoint: CGPointMake(143.5, 135)];
    [bezierPath addLineToPoint: CGPointMake(143.5, 137.5)];
    [bezierPath addLineToPoint: CGPointMake(147, 141)];
    [bezierPath addLineToPoint: CGPointMake(154.25, 148.25)];
    [bezierPath moveToPoint: CGPointMake(96.5, 76.5)];
    [bezierPath addLineToPoint: CGPointMake(85, 85)];
    [bezierPath addLineToPoint: CGPointMake(81.5, 92)];
    [bezierPath addLineToPoint: CGPointMake(70.5, 104.5)];
    [bezierPath addLineToPoint: CGPointMake(64.5, 102)];
    [bezierPath moveToPoint: CGPointMake(96.5, 76.5)];
    [bezierPath addLineToPoint: CGPointMake(92.5, 84)];
    [bezierPath addLineToPoint: CGPointMake(91, 92)];
    [bezierPath moveToPoint: CGPointMake(64.5, 102)];
    [bezierPath addLineToPoint: CGPointMake(49, 122)];
    [bezierPath addLineToPoint: CGPointMake(39, 119.5)];
    [bezierPath moveToPoint: CGPointMake(64.5, 102)];
    [bezierPath addLineToPoint: CGPointMake(64.5, 114.5)];
    [bezierPath addLineToPoint: CGPointMake(66.5, 126)];
    [bezierPath moveToPoint: CGPointMake(39, 119.5)];
    [bezierPath addLineToPoint: CGPointMake(42.5, 125.5)];
    [bezierPath addLineToPoint: CGPointMake(44, 132.5)];
    [bezierPath addLineToPoint: CGPointMake(44, 142)];
    [bezierPath addLineToPoint: CGPointMake(49, 151.5)];
    [bezierPath moveToPoint: CGPointMake(161.5, 155.5)];
    [bezierPath addLineToPoint: CGPointMake(154.25, 148.25)];
    [bezierPath moveToPoint: CGPointMake(238.5, 143)];
    [bezierPath addLineToPoint: CGPointMake(229, 126)];
    [bezierPath addLineToPoint: CGPointMake(227.17, 123)];
    [bezierPath moveToPoint: CGPointMake(154.25, 148.25)];
    [bezierPath addLineToPoint: CGPointMake(168, 143.5)];
    [bezierPath addLineToPoint: CGPointMake(169.16, 145)];
    [bezierPath moveToPoint: CGPointMake(176.5, 154.5)];
    [bezierPath addLineToPoint: CGPointMake(169.16, 145)];
    [bezierPath moveToPoint: CGPointMake(169.16, 145)];
    [bezierPath addLineToPoint: CGPointMake(176.5, 142)];
    [bezierPath addLineToPoint: CGPointMake(183, 145)];
    [bezierPath addLineToPoint: CGPointMake(193, 151.5)];
    [bezierPath addLineToPoint: CGPointMake(203.5, 155.5)];
    [bezierPath addLineToPoint: CGPointMake(212, 162.5)];
    [bezierPath addLineToPoint: CGPointMake(218, 164)];
    [bezierPath addLineToPoint: CGPointMake(233.5, 176)];
    [bezierPath moveToPoint: CGPointMake(88, 117)];
    [bezierPath addLineToPoint: CGPointMake(88, 108.5)];
    [bezierPath addLineToPoint: CGPointMake(89.5, 99)];
    bezierPath.lineWidth = 1;
    bezierPath.miterLimit = 4;
    bezierPath.lineCapStyle = kCGLineCapRound;
    return bezierPath;
}

- (UIBezierPath*)getGrassVector {
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(18.5, 67.5)];
    [bezierPath addLineToPoint: CGPointMake(33, 67.5)];
    [bezierPath addLineToPoint: CGPointMake(47, 64)];
    [bezierPath addLineToPoint: CGPointMake(64.5, 54.5)];
    [bezierPath addLineToPoint: CGPointMake(81.5, 49.5)];
    [bezierPath addLineToPoint: CGPointMake(97.5, 56)];
    [bezierPath addLineToPoint: CGPointMake(110.25, 61.75)];
    [bezierPath moveToPoint: CGPointMake(123, 67.5)];
    [bezierPath addLineToPoint: CGPointMake(110.25, 61.75)];
    [bezierPath moveToPoint: CGPointMake(110.25, 61.75)];
    [bezierPath addLineToPoint: CGPointMake(123, 58)];
    [bezierPath addLineToPoint: CGPointMake(133, 59.5)];
    [bezierPath addLineToPoint: CGPointMake(142.5, 61.75)];
    [bezierPath addLineToPoint: CGPointMake(156, 64)];
    [bezierPath addLineToPoint: CGPointMake(178, 71.5)];
    [bezierPath moveToPoint: CGPointMake(168.5, 74)];
    [bezierPath addLineToPoint: CGPointMake(181, 71.5)];
    [bezierPath addLineToPoint: CGPointMake(191.5, 66)];
    [bezierPath addLineToPoint: CGPointMake(205.5, 66)];
    [bezierPath addLineToPoint: CGPointMake(220, 66)];
    [bezierPath addLineToPoint: CGPointMake(240, 61.75)];
    [bezierPath moveToPoint: CGPointMake(39.5, 95.5)];
    [bezierPath addLineToPoint: CGPointMake(53.5, 95.5)];
    [bezierPath addLineToPoint: CGPointMake(70.5, 92)];
    [bezierPath addLineToPoint: CGPointMake(87.5, 95.5)];
    [bezierPath addLineToPoint: CGPointMake(112, 98.5)];
    [bezierPath addLineToPoint: CGPointMake(156, 103)];
    [bezierPath moveToPoint: CGPointMake(123, 112.5)];
    [bezierPath addLineToPoint: CGPointMake(146.5, 106.5)];
    [bezierPath addLineToPoint: CGPointMake(168.5, 95.5)];
    [bezierPath addLineToPoint: CGPointMake(181, 89)];
    [bezierPath addLineToPoint: CGPointMake(199.5, 89)];
    [bezierPath addLineToPoint: CGPointMake(221.5, 89)];
    [bezierPath moveToPoint: CGPointMake(69, 119)];
    [bezierPath addLineToPoint: CGPointMake(81.5, 116.5)];
    [bezierPath addLineToPoint: CGPointMake(106, 119)];
    [bezierPath addLineToPoint: CGPointMake(134, 120)];
    [bezierPath addLineToPoint: CGPointMake(156, 120)];
    [bezierPath addLineToPoint: CGPointMake(178, 112.5)];
    [bezierPath addLineToPoint: CGPointMake(201, 110)];
    bezierPath.lineWidth = 1;
    bezierPath.miterLimit = 4;
    bezierPath.lineCapStyle = kCGLineCapRound;
    return bezierPath;
}

- (UIBezierPath*)getHillsVector {
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(82.5, 49)];
    [bezierPath addLineToPoint: CGPointMake(84.5, 55.5)];
    [bezierPath addLineToPoint: CGPointMake(85.5, 66.5)];
    [bezierPath addLineToPoint: CGPointMake(83, 85)];
    [bezierPath addLineToPoint: CGPointMake(79.5, 102.5)];
    [bezierPath addLineToPoint: CGPointMake(80, 112)];
    [bezierPath addLineToPoint: CGPointMake(83, 120)];
    [bezierPath moveToPoint: CGPointMake(87.5, 120)];
    [bezierPath addLineToPoint: CGPointMake(88.5, 108.5)];
    [bezierPath moveToPoint: CGPointMake(89.5, 104.5)];
    [bezierPath addLineToPoint: CGPointMake(88.5, 92.5)];
    [bezierPath addLineToPoint: CGPointMake(87.5, 84.5)];
    [bezierPath addLineToPoint: CGPointMake(86.5, 77)];
    [bezierPath moveToPoint: CGPointMake(95, 71.5)];
    [bezierPath addLineToPoint: CGPointMake(97, 79.5)];
    [bezierPath addLineToPoint: CGPointMake(98.5, 90)];
    [bezierPath moveToPoint: CGPointMake(100, 80.5)];
    [bezierPath addLineToPoint: CGPointMake(100.5, 86.5)];
    [bezierPath addLineToPoint: CGPointMake(103, 95.5)];
    [bezierPath addLineToPoint: CGPointMake(105.5, 101.5)];
    [bezierPath moveToPoint: CGPointMake(104, 90)];
    [bezierPath addLineToPoint: CGPointMake(104.5, 94.5)];
    [bezierPath addLineToPoint: CGPointMake(108, 100.5)];
    [bezierPath moveToPoint: CGPointMake(117, 78)];
    [bezierPath addLineToPoint: CGPointMake(118, 85)];
    [bezierPath addLineToPoint: CGPointMake(119.5, 92)];
    [bezierPath addLineToPoint: CGPointMake(122, 97.5)];
    [bezierPath moveToPoint: CGPointMake(125.5, 99)];
    [bezierPath addLineToPoint: CGPointMake(122.5, 93)];
    [bezierPath addLineToPoint: CGPointMake(121, 88)];
    [bezierPath addLineToPoint: CGPointMake(120.5, 83)];
    [bezierPath moveToPoint: CGPointMake(118, 92)];
    [bezierPath addLineToPoint: CGPointMake(116, 86)];
    [bezierPath addLineToPoint: CGPointMake(115, 80)];
    [bezierPath addLineToPoint: CGPointMake(114.5, 72)];
    [bezierPath addLineToPoint: CGPointMake(115, 65)];
    [bezierPath moveToPoint: CGPointMake(58, 54.5)];
    [bezierPath addLineToPoint: CGPointMake(55.5, 62)];
    [bezierPath addLineToPoint: CGPointMake(54.5, 69)];
    [bezierPath addLineToPoint: CGPointMake(54.5, 77)];
    [bezierPath moveToPoint: CGPointMake(52.5, 71.5)];
    [bezierPath addLineToPoint: CGPointMake(53, 63.5)];
    [bezierPath addLineToPoint: CGPointMake(55.5, 54.5)];
    [bezierPath addLineToPoint: CGPointMake(59, 47)];
    [bezierPath moveToPoint: CGPointMake(61.5, 36)];
    [bezierPath addLineToPoint: CGPointMake(57.5, 42)];
    [bezierPath addLineToPoint: CGPointMake(54.5, 48)];
    [bezierPath moveToPoint: CGPointMake(17.5, 77)];
    [bezierPath addLineToPoint: CGPointMake(15.5, 85)];
    [bezierPath addLineToPoint: CGPointMake(12.5, 92.5)];
    [bezierPath addLineToPoint: CGPointMake(9.5, 98)];
    [bezierPath moveToPoint: CGPointMake(20.5, 77)];
    [bezierPath addLineToPoint: CGPointMake(18.5, 84.5)];
    [bezierPath addLineToPoint: CGPointMake(15, 93.5)];
    [bezierPath moveToPoint: CGPointMake(22, 69)];
    [bezierPath addLineToPoint: CGPointMake(21, 74.5)];
    [bezierPath moveToPoint: CGPointMake(35.5, 55.5)];
    [bezierPath addLineToPoint: CGPointMake(33, 65)];
    [bezierPath moveToPoint: CGPointMake(34.5, 68)];
    [bezierPath addLineToPoint: CGPointMake(33, 74.5)];
    [bezierPath addLineToPoint: CGPointMake(32.5, 82)];
    [bezierPath moveToPoint: CGPointMake(31.5, 70.5)];
    [bezierPath addLineToPoint: CGPointMake(30.5, 80)];
    [bezierPath moveToPoint: CGPointMake(41.5, 83)];
    [bezierPath addLineToPoint: CGPointMake(42, 89)];
    [bezierPath moveToPoint: CGPointMake(43.5, 90)];
    [bezierPath addLineToPoint: CGPointMake(43.5, 104.5)];
    [bezierPath moveToPoint: CGPointMake(59, 70.5)];
    [bezierPath addLineToPoint: CGPointMake(59.5, 81.5)];
    [bezierPath addLineToPoint: CGPointMake(60.5, 90)];
    [bezierPath moveToPoint: CGPointMake(170.5, 37)];
    [bezierPath addLineToPoint: CGPointMake(171, 41.5)];
    [bezierPath addLineToPoint: CGPointMake(173.5, 48)];
    [bezierPath addLineToPoint: CGPointMake(174.04, 50.5)];
    [bezierPath moveToPoint: CGPointMake(173.5, 62.5)];
    [bezierPath addLineToPoint: CGPointMake(175, 55)];
    [bezierPath addLineToPoint: CGPointMake(174.04, 50.5)];
    [bezierPath moveToPoint: CGPointMake(175, 36.5)];
    [bezierPath addLineToPoint: CGPointMake(174.5, 42.5)];
    [bezierPath addLineToPoint: CGPointMake(174.04, 50.5)];
    [bezierPath moveToPoint: CGPointMake(186.5, 29.5)];
    [bezierPath addLineToPoint: CGPointMake(184.5, 37)];
    [bezierPath addLineToPoint: CGPointMake(182.5, 44.5)];
    [bezierPath moveToPoint: CGPointMake(205, 40)];
    [bezierPath addLineToPoint: CGPointMake(206.5, 49.5)];
    [bezierPath addLineToPoint: CGPointMake(212.5, 62.5)];
    [bezierPath moveToPoint: CGPointMake(184.5, 84.5)];
    [bezierPath addLineToPoint: CGPointMake(189, 92)];
    [bezierPath addLineToPoint: CGPointMake(194, 97.5)];
    [bezierPath moveToPoint: CGPointMake(182.5, 98)];
    [bezierPath addLineToPoint: CGPointMake(177, 94.5)];
    [bezierPath moveToPoint: CGPointMake(232.5, 47)];
    [bezierPath addLineToPoint: CGPointMake(232.5, 50.5)];
    [bezierPath moveToPoint: CGPointMake(237, 49.5)];
    [bezierPath addLineToPoint: CGPointMake(237, 54.5)];
    [bezierPath addLineToPoint: CGPointMake(239.5, 58.5)];
    [bezierPath moveToPoint: CGPointMake(98.5, 32)];
    [bezierPath addLineToPoint: CGPointMake(100.5, 41.5)];
    [bezierPath addLineToPoint: CGPointMake(105.5, 44.5)];
    [bezierPath addLineToPoint: CGPointMake(108, 50.5)];
    [bezierPath moveToPoint: CGPointMake(198, 12.5)];
    [bezierPath addLineToPoint: CGPointMake(200, 16)];
    [bezierPath addLineToPoint: CGPointMake(200, 20)];
    [bezierPath moveToPoint: CGPointMake(194, 18.5)];
    [bezierPath addLineToPoint: CGPointMake(192.5, 28.5)];
    [bezierPath moveToPoint: CGPointMake(202.5, 92)];
    [bezierPath addLineToPoint: CGPointMake(205, 93.5)];
    [bezierPath addLineToPoint: CGPointMake(210, 95.5)];
    [bezierPath addLineToPoint: CGPointMake(218.5, 102.5)];
    [bezierPath moveToPoint: CGPointMake(138.5, 70.5)];
    [bezierPath addLineToPoint: CGPointMake(141, 77)];
    [bezierPath addLineToPoint: CGPointMake(147.5, 84.5)];
    bezierPath.lineWidth = 0.5;
    bezierPath.miterLimit = 4;
    bezierPath.lineCapStyle = kCGLineCapRound;
    return bezierPath;
}

@end
